-- SUPERSEDED -- do not run.
--
-- This file was an early hand-written 22-rule skeleton aligned to Collection
-- Manifest v0.7. The applied, authoritative QA seed now lives in the migration
-- set and is generated from the machine-readable contract:
--
--   supabase/migrations/020_qa_contract_v0_1.sql   (generated; APPLIED seed)
--   scripts/gen_qa_seed.py                          (generator)
--   docs/contracts/qa-rules-v0_1.json               (21 core rules + thresholds)
--   docs/contracts/qa-wave-acceptance-rules-v0_1.json (58 wave-acceptance rules)
--
-- Migration 020 seeds ops.qa_contract_version (SED_WAVE_QA v0.1) and 80 ops.qa_rule
-- rows (21 core + 58 wave-acceptance + 1 contract-meta). Running this skeleton
-- afterward would re-introduce stale rule text, so it is intentionally left inert.
--
-- Retained only for provenance; see docs/AUTHORITATIVE-ARTIFACTS.md.
