#!/usr/bin/env python3
"""Generate supabase/migrations/020_qa_contract_v0_1.sql from the authoritative QA contract.

Inputs (authoritative machine-readable, in-repo):
  * docs/contracts/qa-rules-v0_1.json                 (contract + 21 qa_rules + thresholds)
  * docs/contracts/qa-wave-acceptance-rules-v0_1.json (contract-level config + 58 wave rules)

Output: ops.qa_contract_version (SED_WAVE_QA v0.1) + ops.qa_rule rows:
  * 21 core QA rules (rule_config = {})
  * 58 wave-acceptance rules (rule_config carries stage/condition/metric/threshold/action/rationale)
  *  1 QA-META-CONTRACT row (scope=contract, severity=info) carrying the contract-level
     thresholds / denominators / status_logic / financial_reconciliation / analysis_eligibility
     so the wave-acceptance semantics are queryable in-DB.

Replaces the earlier hand-written 22-rule skeleton (supabase/seeds/qa_rules_v0_1.sql),
which was aligned to manifest v0.7 and is superseded by these authoritative JSON files.
Idempotent: ON CONFLICT DO UPDATE keeps the row set current on re-run.
"""
from __future__ import annotations
import hashlib, json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
QA_RULES = ROOT / "docs" / "contracts" / "qa-rules-v0_1.json"
WAVE_RULES = ROOT / "docs" / "contracts" / "qa-wave-acceptance-rules-v0_1.json"
OUT = ROOT / "supabase" / "migrations" / "020_qa_contract_v0_1.sql"


def q(v) -> str:
    if v is None or v == "":
        return "null"
    return "'" + str(v).replace("'", "''") + "'"


def qj(obj) -> str:
    return "'" + json.dumps(obj, sort_keys=True, ensure_ascii=False).replace("'", "''") + "'::jsonb"


SEV = {"info", "warning", "error", "critical"}


def norm_sev(s: str) -> str:
    s = (s or "").lower().strip()
    return s if s in SEV else "error"


def main() -> None:
    qa = json.loads(QA_RULES.read_text())
    wave = json.loads(WAVE_RULES.read_text())
    wave_sha = hashlib.sha256(WAVE_RULES.read_bytes()).hexdigest()
    qa_sha = hashlib.sha256(QA_RULES.read_bytes()).hexdigest()

    out: list[str] = []
    A = out.append
    A("-- Migration 020_qa_contract_v0_1")
    A("-- SED Local Search Intelligence Platform -- Operational QA / Wave Acceptance Contract v0.1")
    A("--")
    A("-- GENERATED by scripts/gen_qa_seed.py from the authoritative machine-readable QA contract:")
    A("--   docs/contracts/qa-rules-v0_1.json                 (21 core rules + thresholds)")
    A("--   docs/contracts/qa-wave-acceptance-rules-v0_1.json (58 wave-acceptance rules + config)")
    A("-- Supersedes the hand-written skeleton at supabase/seeds/qa_rules_v0_1.sql. Do NOT hand-edit.")
    A(f"-- qa-rules sha256           = {qa_sha}")
    A(f"-- wave-acceptance sha256    = {wave_sha}")
    A("")

    # contract version
    notes = (f"Operational QA / Wave Acceptance Contract v0.1. Machine-readable sources: "
             f"qa-rules-v0_1.json (sha256 {qa_sha}), qa-wave-acceptance-rules-v0_1.json "
             f"(sha256 {wave_sha}). PARTIAL thresholds: overall>=99.5%, surface>=99.0%, "
             f"stratum>=95% (>=20 executable jobs), no critical integrity failure.")
    A("insert into ops.qa_contract_version (contract_code, version_code, status, artifact_uri, artifact_sha256, notes)")
    A(f"values ('{qa['contract_code']}', '{qa['version_code']}', {q(qa.get('status','draft'))},")
    A("  'docs/contracts/qa-wave-acceptance-rules-v0_1.json',")
    A(f"  '{wave_sha}', {q(notes)})")
    A("on conflict (contract_code, version_code) do update set")
    A("  status = excluded.status, artifact_uri = excluded.artifact_uri,")
    A("  artifact_sha256 = excluded.artifact_sha256, notes = excluded.notes;")
    A("")

    cvq = ("(select qa_contract_version_id from ops.qa_contract_version "
           f"where contract_code = '{qa['contract_code']}' and version_code = '{qa['version_code']}')")

    # assemble rule rows: (rule_code, scope, severity, description, rule_config)
    rows = []
    for r in qa["rules"]:
        rows.append((r["rule_code"], r.get("scope", ""), norm_sev(r.get("severity")),
                     r.get("description", ""), {}))
    for r in wave["rules"]:
        cfg = {k: r.get(k) for k in ("stage", "metric", "threshold", "action", "rationale")}
        desc = r.get("condition") or r.get("rationale") or r["rule_code"]
        rows.append((r["rule_code"], r.get("scope", ""), norm_sev(r.get("severity")), desc, cfg))
    # contract-level meta row
    meta_cfg = {
        "thresholds_qa_rules": qa.get("thresholds", {}),
        "thresholds_wave": wave.get("thresholds", {}),
        "denominators": wave.get("denominators", {}),
        "status_logic": wave.get("status_logic", {}),
        "financial_reconciliation": wave.get("financial_reconciliation", {}),
        "analysis_eligibility": wave.get("analysis_eligibility", {}),
        "contract": wave.get("contract", {}),
    }
    rows.append(("QA-META-CONTRACT", "contract", "info",
                 "Contract-level thresholds, denominators, status logic, financial reconciliation, "
                 "and analysis eligibility (see rule_config).", meta_cfg))

    codes = [r[0] for r in rows]
    assert len(codes) == len(set(codes)), "duplicate rule_code"

    A(f"-- {len(rows)} qa_rule rows (21 core + 58 wave-acceptance + 1 contract-meta) ----------")
    A("insert into ops.qa_rule (qa_contract_version_id, rule_code, scope, severity, description, rule_config)")
    A("select cv.qa_contract_version_id, v.rule_code, v.scope, v.severity, v.description, v.rule_config")
    A("from (values")
    vals = []
    for code, scope, sev, desc, cfg in rows:
        vals.append(f"  ({q(code)}, {q(scope)}, {q(sev)}, {q(desc)}, {qj(cfg)})")
    A(",\n".join(vals))
    A(") as v(rule_code, scope, severity, description, rule_config)")
    A(f"cross join {cvq} cv(qa_contract_version_id)")
    A("on conflict (qa_contract_version_id, rule_code) do update set")
    A("  scope = excluded.scope, severity = excluded.severity,")
    A("  description = excluded.description, rule_config = excluded.rule_config;")
    A("")

    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT}: {len(rows)} rules")


if __name__ == "__main__":
    main()
