#!/usr/bin/env python3
"""Generate supabase/migrations/019_manifest_v1_data.sql from the frozen Manifest v1.0.

Inputs (authoritative, in-repo, byte/SHA verified on import):
  * manifest/SED_Collection_Manifest_v1_0.json
  * manifest/SED_Coordinates_GeoEligible_v1_0.csv  (1,100 coordinates + geometry)

Output: a deterministic, idempotent seed (INSERT ... SELECT ... FROM (VALUES ...)
joined to natural keys, ON CONFLICT DO NOTHING) loading the frozen manifest into
the manifest/ops schemas. It does NOT invent methodology; it loads the frozen
plan verbatim.

Loaded: methodology_version, 25 industries, 50 markets, methodology_industry/
market ordinals, 2 geometry_versions (MAPORG13_V1, AIO9_V1), 22 geometry_points,
1,100 market_coordinates (1,000 eligible_land / 91 structural_water_exclusion /
9 outside_country_exclusion), 600 treatments (100 Google query + 250 AIO query +
250 ChatGPT prompt), 700 surface_treatments, 1 provider (DataForSEO), 4
provider_profiles, 4 surface_configs, and the fixed weekly Sentinel panel_subset
(5 industries x 10 markets).
"""
from __future__ import annotations
import csv, hashlib, json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "manifest" / "SED_Collection_Manifest_v1_0.json"
COORDS_CSV = ROOT / "manifest" / "SED_Coordinates_GeoEligible_v1_0.csv"
OUT = ROOT / "supabase" / "migrations" / "019_manifest_v1_data.sql"

METH_CODE = "MANIFEST_V1_0"
FREEZE_TS = "2026-09-09T00:00:00Z"
CLASSIFIER = "SED_GEO_ELIGIBILITY_CENSUS_2025_V1"
WATER_SOURCE = "US Census Bureau 2025 TIGER/Line AREAWATER"


def q(v) -> str:
    """SQL literal for text/null."""
    if v is None or v == "":
        return "null"
    return "'" + str(v).replace("'", "''") + "'"


def qj(obj) -> str:
    """SQL jsonb literal."""
    return "'" + json.dumps(obj, sort_keys=True, ensure_ascii=False).replace("'", "''") + "'::jsonb"


def num(v) -> str:
    if v is None or v == "" or str(v).lower() == "none":
        return "null"
    return str(v)


def bool_sql(v) -> str:
    if isinstance(v, str):
        v = v.strip().lower() == "true"
    return "true" if v else "false"


def main() -> None:
    m = json.loads(MANIFEST.read_text())
    manifest_sha = hashlib.sha256(MANIFEST.read_bytes()).hexdigest()
    market_centers = {mc["market_id"]: mc for mc in m["market_centers"]}
    out: list[str] = []
    A = out.append

    A("-- Migration 019_manifest_v1_data")
    A("-- SED Local Search Intelligence Platform -- Frozen Manifest v1.0 data seed")
    A("--")
    A("-- GENERATED by scripts/gen_manifest_seed.py from the frozen, SHA-verified")
    A("-- Manifest v1.0 (manifest/SED_Collection_Manifest_v1_0.json) and its geography")
    A("-- (manifest/SED_Coordinates_GeoEligible_v1_0.csv). Do NOT hand-edit; regenerate.")
    A("-- Idempotent: INSERT ... SELECT joined to natural keys, ON CONFLICT DO NOTHING.")
    A(f"-- manifest_sha256 = {manifest_sha}")
    A("--")
    A("-- Coordinate reconciliation target (manifest/SED_Geo_Eligibility_Report_v1_0.json):")
    A("--   1,100 coordinates -> 1,000 eligible_land / 91 structural_water_exclusion / 9 outside_country_exclusion")
    A("")

    # ---- methodology_version ----------------------------------------------
    A("-- methodology_version -----------------------------------------------------")
    A("insert into manifest.methodology_version")
    A("  (methodology_code, status, effective_from, frozen_at, manifest_sha256,")
    A("   manifest_artifact_uri, governing_handoff_drive_id, governing_parent_prd_drive_id, notes)")
    A("values (")
    A(f"  '{METH_CODE}', 'frozen', '{FREEZE_TS}', '{FREEZE_TS}', '{manifest_sha}',")
    A("  'manifest/SED_Collection_Manifest_v1_0.json',")
    A("  '1GrlD5M1WcAmmdaf8PCYCpj6P4V87Ezm1', '1Y5CmSWDpSKryfkmcbPh25UG_yfyyvwZV2hdkh1hh3Sc',")
    A("  'Frozen executable Collection Manifest v1.0 (25 industries x 50 markets); "
      "civic-center anchors + water/country geography applied before first collection.')")
    A("on conflict (methodology_code) do nothing;")
    A("")

    mv_join = ("join manifest.methodology_version mv on mv.methodology_code = "
               f"'{METH_CODE}'")

    # ---- industries -------------------------------------------------------
    A("-- industries -------------------------------------------------------------")
    rows = []
    for ind in m["industries"]:
        rows.append(f"  ({q(ind['industry_id'])}, {q(ind['industry_name'])}, "
                    f"{q(ind['canonical_service_term'])}, {q(ind.get('vertical_group'))})")
    A("insert into manifest.industry (industry_code, industry_name, canonical_service_term, vertical_group)")
    A("values")
    A(",\n".join(rows))
    A("on conflict (industry_code) do nothing;")
    A("")

    # ---- markets ----------------------------------------------------------
    A("-- markets ----------------------------------------------------------------")
    rows = []
    for mk in m["markets"]:
        mc = market_centers.get(mk["market_id"], {})
        meta = {
            "census_place_name": mk.get("census_place_name"),
            "census_geoidfq": mk.get("census_geoidfq"),
            "region_stratum": mk.get("region_stratum"),
            "size_stratum_planning": mk.get("size_stratum_planning"),
            "water_exposure_planning": mk.get("water_exposure_planning"),
            "morphology_planning": mk.get("morphology_planning"),
            "center_anchor_label": mc.get("center_anchor_label"),
            "center_anchor_type": mc.get("center_anchor_type"),
            "center_status": mk.get("center_status"),
            "gazetteer_center_lat": mc.get("gazetteer_center_lat"),
            "gazetteer_center_lon": mc.get("gazetteer_center_lon"),
        }
        rows.append(
            f"  ({q(mk['market_id'])}, {q(mk['city'])}, {q(mk['state'])}, "
            f"{q(mk.get('country','US'))}, {q(mk.get('census_geoid'))}, "
            f"{num(mk.get('center_lat'))}, {num(mk.get('center_lon'))}, "
            f"{q(mc.get('source_url'))}, {q(mk.get('market_center_method_version'))}, {qj(meta)})"
        )
    A("insert into manifest.market (market_code, city, state_region, country_code, census_place_geoid,")
    A("  center_lat, center_lon, center_source, center_method_version, metadata)")
    A("values")
    A(",\n".join(rows))
    A("on conflict (market_code) do nothing;")
    A("")

    # ---- methodology_industry / methodology_market ------------------------
    A("-- methodology_industry ordinals ------------------------------------------")
    rows = [f"  ({q(ind['industry_id'])}, {i+1})" for i, ind in enumerate(m["industries"])]
    A("insert into manifest.methodology_industry (methodology_version_id, industry_id, ordinal, approval_basis)")
    A("select mv.methodology_version_id, i.industry_id, v.ordinal, 'Frozen Manifest v1.0'")
    A("from (values")
    A(",\n".join(rows))
    A(") as v(industry_code, ordinal)")
    A("join manifest.industry i on i.industry_code = v.industry_code")
    A(mv_join)
    A("on conflict do nothing;")
    A("")

    A("-- methodology_market ordinals --------------------------------------------")
    rows = [f"  ({q(mk['market_id'])}, {i+1})" for i, mk in enumerate(m["markets"])]
    A("insert into manifest.methodology_market (methodology_version_id, market_id, ordinal, approval_basis)")
    A("select mv.methodology_version_id, mk.market_id, v.ordinal, 'Frozen Manifest v1.0'")
    A("from (values")
    A(",\n".join(rows))
    A(") as v(market_code, ordinal)")
    A("join manifest.market mk on mk.market_code = v.market_code")
    A(mv_join)
    A("on conflict do nothing;")
    A("")

    # ---- geometry_version -------------------------------------------------
    A("-- geometry_version -------------------------------------------------------")
    geoms = [
        ("MAPORG13_V1", "Maps/Organic 13-point (center + N/E/S/W @1/3/5 mi)", "maps_organic"),
        ("AIO9_V1", "AIO 9-point (center + N/E/S/W @2.5/5 mi)", "aio"),
    ]
    rows = [f"  ({q(gc)}, {q(gn)}, {q(sg)})" for gc, gn, sg in geoms]
    A("insert into manifest.geometry_version (methodology_version_id, geometry_code, geometry_name,")
    A("  surface_group, generation_method, water_mask_version, status)")
    A(f"select mv.methodology_version_id, v.geometry_code, v.geometry_name, v.surface_group,")
    A(f"  'WGS84_GEODESIC_DIRECT', '{CLASSIFIER}', 'frozen'")
    A("from (values")
    A(",\n".join(rows))
    A(") as v(geometry_code, geometry_name, surface_group)")
    A(mv_join)
    A("on conflict (methodology_version_id, geometry_code) do nothing;")
    A("")

    # ---- geometry_point (derive distinct points per geometry from CSV) -----
    coord_rows = list(csv.DictReader(COORDS_CSV.open()))
    gpoints: dict[str, dict] = {}
    for r in coord_rows:
        key = (r["geometry_id"], r["point_id"])
        if key not in gpoints:
            gpoints[key] = r
    # deterministic order: geometry, then first-seen order
    order: dict[str, int] = {}
    A("-- geometry_point --------------------------------------------------------")
    rows = []
    for (gid, pid), r in gpoints.items():
        order[gid] = order.get(gid, 0) + 1
        ordinal = order[gid]
        rows.append(
            f"  ({q(gid)}, {q(pid)}, {q(r['label'])}, {num(r['bearing_deg'])}, "
            f"{num(r['distance_miles'])}, {bool_sql(r['full_geometry_member'])}, "
            f"{bool_sql(r['nested9_candidate_member'])}, {bool_sql(r['incremental4_member'])}, {ordinal})"
        )
    A("insert into manifest.geometry_point (geometry_version_id, point_code, point_label, bearing_deg,")
    A("  distance_miles, full_geometry_member, nested_candidate_member, incremental_member, ordinal)")
    A("select gv.geometry_version_id, v.point_code, v.point_label, v.bearing_deg, v.distance_miles,")
    A("  v.full_geometry_member, v.nested_candidate_member, v.incremental_member, v.ordinal")
    A("from (values")
    A(",\n".join(rows))
    A(") as v(geometry_code, point_code, point_label, bearing_deg, distance_miles,")
    A("       full_geometry_member, nested_candidate_member, incremental_member, ordinal)")
    A("join manifest.geometry_version gv on gv.geometry_code = v.geometry_code")
    A(mv_join.replace("mv.methodology_code", "gv.methodology_version_id = mv.methodology_version_id and mv.methodology_code"))
    A("on conflict (geometry_version_id, point_code) do nothing;")
    A("")

    # ---- market_coordinate (1,100) ---------------------------------------
    A("-- market_coordinate (1,100: 1,000 eligible / 91 water / 9 outside-country) --")
    rows = []
    counts = {"eligible_land": 0, "structural_water_exclusion": 0, "outside_country_exclusion": 0}
    for r in coord_rows:
        if r["country_boundary_status"] != "in_country":
            elig = "outside_country_exclusion"
            reason = "Non-center treatment point outside US international boundary (relocation prohibited)."
            wsrc = "US Census Bureau 2025 TIGER/Line International Boundary"
        elif r["water_eligibility_status"] == "structural_water_exclusion":
            elig = "structural_water_exclusion"
            names = r.get("matched_names") or ""
            mtfccs = r.get("matched_mtfccs") or ""
            reason = ("Structural water exclusion (Census 2025 AREAWATER): "
                      + (f"{names} " if names else "") + (f"[{mtfccs}]" if mtfccs else "")).strip()
            if not reason.endswith(")"):
                reason = reason or "Structural water exclusion (Census 2025 AREAWATER)."
            wsrc = WATER_SOURCE
        else:
            elig = "eligible_land"
            reason = None
            wsrc = None
        counts[elig] += 1
        wname = r.get("matched_names") if elig == "structural_water_exclusion" else None
        wmtfcc = r.get("matched_mtfccs") if elig == "structural_water_exclusion" else None
        whydro = r.get("matched_hydroids") if elig == "structural_water_exclusion" else None
        rows.append(
            f"  ({q(r['market_id'])}, {q(r['geometry_id'])}, {q(r['point_id'])}, "
            f"{r['latitude']}, {r['longitude']}, '{elig}', {q(reason)}, "
            f"{q(wname)}, {q(wmtfcc)}, {q(whydro)}, {q(wsrc)}, "
            f"{q(CLASSIFIER if elig != 'eligible_land' else None)})"
        )
    assert counts == {"eligible_land": 1000, "structural_water_exclusion": 91,
                      "outside_country_exclusion": 9}, counts
    A("insert into manifest.market_coordinate (methodology_version_id, market_id, geometry_point_id,")
    A("  latitude, longitude, eligibility, structural_exclusion_reason, water_feature_name,")
    A("  water_feature_mtfcc, water_feature_id, water_mask_source, water_mask_version, eligibility_decided_at)")
    A("select mv.methodology_version_id, mk.market_id, gp.geometry_point_id, v.latitude, v.longitude,")
    A("  v.eligibility::manifest.coordinate_eligibility, v.reason, v.wname, v.wmtfcc, v.whydro,")
    A(f"  v.wsrc, v.wmask, '{FREEZE_TS}'")
    A("from (values")
    A(",\n".join(rows))
    A(") as v(market_code, geometry_code, point_code, latitude, longitude, eligibility, reason,")
    A("       wname, wmtfcc, whydro, wsrc, wmask)")
    A("join manifest.market mk on mk.market_code = v.market_code")
    A("join manifest.geometry_version gv on gv.geometry_code = v.geometry_code")
    A("join manifest.geometry_point gp on gp.geometry_version_id = gv.geometry_version_id and gp.point_code = v.point_code")
    A("join manifest.methodology_version mv on mv.methodology_version_id = gv.methodology_version_id and mv.methodology_code = '" + METH_CODE + "'")
    A("on conflict (methodology_version_id, market_id, geometry_point_id) do nothing;")
    A("")

    # ---- treatments -------------------------------------------------------
    # Build a canonical treatment list: (industry_code, set_code, code, kind, family,
    #   core_query_class, template, seq_in_set, city_slot, approval_basis, meta)
    treatments = []
    for gqt in m["google_queries"]:
        seq = int(gqt["query_class"][1:])  # Q1->1
        treatments.append(dict(
            industry=gqt["industry_id"], set_code="GOOGLE_QUERY_V1", code=gqt["query_class"],
            kind="query", family=gqt.get("treatment_role"), core_query_class=gqt["query_class"],
            template=gqt["query_text_template"], seq=seq,
            city_slot=bool(gqt.get("city_slot_required")),
            approval=gqt.get("query_status"),
            meta={"source_id": gqt["query_id"], "treatment_role": gqt.get("treatment_role"),
                  "source_methodology_version": gqt.get("methodology_version")},
        ))
    for aq in m["aio_query_registry"]:
        treatments.append(dict(
            industry=aq["industry_id"], set_code="AIO_QUERY_V1", code=aq["condition_id"],
            kind="query", family=aq.get("condition_role"), core_query_class=None,
            template=aq["query_template"], seq=int(aq["condition_order"]),
            city_slot=bool(aq.get("city_slot_required")),
            approval=aq.get("literal_status"),
            meta={"source_id": aq["aio_query_id"], "condition_role": aq.get("condition_role"),
                  "condition_id": aq["condition_id"],
                  "source_methodology_version": aq.get("methodology_version")},
        ))
    for cp in m["chatgpt_prompt_registry"]:
        treatments.append(dict(
            industry=cp["industry_id"], set_code="CHATGPT_PROMPT_V1", code=cp["condition_id"],
            kind="prompt", family=cp.get("prompt_family"), core_query_class=None,
            template=cp["prompt_template"], seq=int(cp["condition_order"]),
            city_slot=("[CITY]" in cp["prompt_template"]),
            approval=cp.get("literal_status"),
            meta={"source_id": cp["chatgpt_prompt_id"], "condition_role": cp.get("condition_role"),
                  "prompt_family": cp.get("prompt_family"),
                  "fresh_context_replicates": cp.get("fresh_context_replicates"),
                  "source_methodology_version": cp.get("methodology_version")},
        ))

    A(f"-- treatments ({len(treatments)}: 100 Google query + 250 AIO query + 250 ChatGPT prompt) --")
    rows = []
    for t in treatments:
        rows.append(
            f"  ({q(t['industry'])}, {q(t['set_code'])}, {q(t['code'])}, {q(t['kind'])}, "
            f"{q(t['family'])}, {q(t['core_query_class'])}, {q(t['template'])}, {t['seq']}, "
            f"{bool_sql(t['city_slot'])}, {q(t['approval'])}, {qj(t['meta'])})"
        )
    A("insert into manifest.treatment (methodology_version_id, industry_id, treatment_set_code,")
    A("  treatment_code, treatment_kind, family, core_query_class, exact_template, sequence,")
    A("  city_slot_required, is_locked, approval_basis, metadata)")
    A("select mv.methodology_version_id, i.industry_id, v.set_code, v.code,")
    A("  v.kind::manifest.treatment_kind, v.family, v.core_query_class, v.template, v.seq,")
    A("  v.city_slot, true, v.approval, v.meta")
    A("from (values")
    A(",\n".join(rows))
    A(") as v(industry_code, set_code, code, kind, family, core_query_class, template, seq,")
    A("       city_slot, approval, meta)")
    A("join manifest.industry i on i.industry_code = v.industry_code")
    A(mv_join)
    A("on conflict (methodology_version_id, industry_id, treatment_set_code, treatment_code) do nothing;")
    A("")

    # ---- surface_treatment (700) -----------------------------------------
    # maps + organic -> GOOGLE_QUERY_V1; aio -> AIO_QUERY_V1; chatgpt -> CHATGPT_PROMPT_V1
    surf_map = {
        "maps": "GOOGLE_QUERY_V1", "organic": "GOOGLE_QUERY_V1",
        "aio": "AIO_QUERY_V1", "chatgpt": "CHATGPT_PROMPT_V1",
    }
    A("-- surface_treatment (700) ------------------------------------------------")
    rows = []
    for surface, set_code in surf_map.items():
        seq = 0
        for t in treatments:
            if t["set_code"] != set_code:
                continue
            seq += 1
            rows.append(f"  ({q(surface)}, {q(t['industry'])}, {q(t['set_code'])}, {q(t['code'])}, {seq})")
    A("insert into manifest.surface_treatment (methodology_version_id, surface_id, treatment_id, sequence, active)")
    A("select mv.methodology_version_id, s.surface_id, t.treatment_id, v.seq, true")
    A("from (values")
    A(",\n".join(rows))
    A(") as v(surface_code, industry_code, set_code, code, seq)")
    A("join manifest.surface s on s.surface_code = v.surface_code")
    A("join manifest.industry i on i.industry_code = v.industry_code")
    A(mv_join)
    A("join manifest.treatment t on t.methodology_version_id = mv.methodology_version_id")
    A("  and t.industry_id = i.industry_id and t.treatment_set_code = v.set_code and t.treatment_code = v.code")
    A("on conflict (methodology_version_id, surface_id, treatment_id) do nothing;")
    A("")

    # ---- provider + provider_profile + surface_config --------------------
    A("-- provider ---------------------------------------------------------------")
    A("insert into ops.provider (provider_code, provider_name, provider_kind, homepage_url)")
    A("values ('dataforseo', 'DataForSEO', 'serp_ai_api', 'https://dataforseo.com/')")
    A("on conflict (provider_code) do nothing;")
    A("")

    ps = m["provider_settings"]
    profiles = [
        ("maps", "DFS_MAPS_V1", "location_coordinate", "{lat},{lon},17z", 10),
        ("organic", "DFS_ORGANIC_V1", "location_coordinate", "{lat},{lon},200", 10),
        ("aio", "DFS_AIO_V1", "location_coordinate", "{lat},{lon},9z", None),
        ("chatgpt", "DFS_CHATGPT_V1", "location_code", "2840", None),
    ]
    A("-- provider_profile (4) ---------------------------------------------------")
    rows = []
    for surface, code, loc_mode, loc_tmpl, depth in profiles:
        s = ps[surface]
        settings_json = json.dumps(s, sort_keys=True, ensure_ascii=False)
        settings_sha = hashlib.sha256(settings_json.encode()).hexdigest()
        rows.append(
            f"  ({q(surface)}, {q(code)}, {q(s.get('method'))}, {q(s.get('post_endpoint'))}, "
            f"{q(s.get('get_endpoint'))}, {q(s.get('language_code'))}, {q(s.get('device'))}, "
            f"{q(s.get('os'))}, {q(loc_mode)}, {q(loc_tmpl)}, {num(depth)}, "
            f"{num(s.get('priority'))}, {num(s.get('max_tasks_per_post'))}, {qj(s)}, '{settings_sha}')"
        )
    A("insert into manifest.provider_profile (methodology_version_id, surface_id, provider_id, profile_code,")
    A("  method, post_endpoint, get_endpoint, language_code, device, operating_system, location_mode,")
    A("  location_template, result_depth, priority, max_tasks_per_post, settings, settings_sha256)")
    A("select mv.methodology_version_id, s.surface_id, p.provider_id, v.profile_code, v.method,")
    A("  v.post_endpoint, v.get_endpoint, v.language_code, v.device, v.os, v.location_mode,")
    A("  v.location_template, v.result_depth, v.priority, v.max_tasks_per_post, v.settings, v.settings_sha256")
    A("from (values")
    A(",\n".join(rows))
    A(") as v(surface_code, profile_code, method, post_endpoint, get_endpoint, language_code, device, os,")
    A("       location_mode, location_template, result_depth, priority, max_tasks_per_post, settings, settings_sha256)")
    A("join manifest.surface s on s.surface_code = v.surface_code")
    A("cross join ops.provider p")
    A(mv_join)
    A("where p.provider_code = 'dataforseo'")
    A("on conflict (methodology_version_id, profile_code) do nothing;")
    A("")

    A("-- surface_config (4) -----------------------------------------------------")
    sconf = [
        ("maps", "DFS_MAPS_V1", "MAPORG13_V1", 1, 10),
        ("organic", "DFS_ORGANIC_V1", "MAPORG13_V1", 1, 10),
        ("aio", "DFS_AIO_V1", "AIO9_V1", 1, None),
        ("chatgpt", "DFS_CHATGPT_V1", None, 3, None),
    ]
    rows = []
    for surface, profile, geom, reps, depth in sconf:
        rows.append(f"  ({q(surface)}, {q(profile)}, {q(geom)}, {reps}, {num(depth)})")
    A("insert into manifest.surface_config (methodology_version_id, surface_id, provider_profile_id,")
    A("  geometry_version_id, full_panel_cadence, sentinel_cadence, replicates, result_depth, raw_response_required)")
    A("select mv.methodology_version_id, s.surface_id, pp.provider_profile_id,")
    A("  gv.geometry_version_id, 'monthly', 'weekly', v.replicates, v.result_depth, true")
    A("from (values")
    A(",\n".join(rows))
    A(") as v(surface_code, profile_code, geometry_code, replicates, result_depth)")
    A("join manifest.surface s on s.surface_code = v.surface_code")
    A(mv_join)
    A("join manifest.provider_profile pp on pp.methodology_version_id = mv.methodology_version_id and pp.profile_code = v.profile_code")
    A("left join manifest.geometry_version gv on gv.methodology_version_id = mv.methodology_version_id and gv.geometry_code = v.geometry_code")
    A("on conflict (methodology_version_id, surface_id) do nothing;")
    A("")

    # ---- panel_subset (Sentinel) -----------------------------------------
    sen = m["sentinel"]
    A("-- panel_subset: fixed weekly Sentinel (5 industries x 10 markets) --------")
    A("insert into manifest.panel_subset (methodology_version_id, subset_code, subset_kind, fixed_membership, description)")
    A("select mv.methodology_version_id, 'SENTINEL_V1', 'sentinel', true,")
    A("  'Fixed weekly Research Sentinel: 5 industries x 10 markets (monthly wave doubles as that week''s Sentinel).'")
    A(f"from manifest.methodology_version mv where mv.methodology_code = '{METH_CODE}'")
    A("on conflict (methodology_version_id, subset_code) do nothing;")
    A("")

    rows = [f"  ({q(ind)}, {i+1})" for i, ind in enumerate(sen["industries"])]
    A("insert into manifest.panel_subset_industry (panel_subset_id, industry_id, ordinal)")
    A("select ps.panel_subset_id, i.industry_id, v.ordinal")
    A("from (values")
    A(",\n".join(rows))
    A(") as v(industry_code, ordinal)")
    A("join manifest.industry i on i.industry_code = v.industry_code")
    A(mv_join)
    A("join manifest.panel_subset ps on ps.methodology_version_id = mv.methodology_version_id and ps.subset_code = 'SENTINEL_V1'")
    A("on conflict do nothing;")
    A("")

    rows = [f"  ({q(mk)}, {i+1})" for i, mk in enumerate(sen["markets"])]
    A("insert into manifest.panel_subset_market (panel_subset_id, market_id, ordinal)")
    A("select ps.panel_subset_id, mk.market_id, v.ordinal")
    A("from (values")
    A(",\n".join(rows))
    A(") as v(market_code, ordinal)")
    A("join manifest.market mk on mk.market_code = v.market_code")
    A(mv_join)
    A("join manifest.panel_subset ps on ps.methodology_version_id = mv.methodology_version_id and ps.subset_code = 'SENTINEL_V1'")
    A("on conflict do nothing;")
    A("")

    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT} ({len(out)} lines)")
    print(f"coordinate counts: {counts}")
    print(f"treatments: {len(treatments)}")


if __name__ == "__main__":
    main()
