#!/usr/bin/env python3
"""Generate supabase/migrations/022_amend_maps_zoom_14z.sql — pilot methodology amendment.

Stage-1 pilot finding: the Maps coordinate zoom shipped in Manifest v1.0
(`location_coordinate: {lat},{lon},17z`, tagged PENDING_EXACT_ENDPOINT_LOCK) returns
DataForSEO status 40102 "No Search Results" for dense queries. A zoom sweep at the
MKT008 (Vancouver WA) center for "locksmith near me" showed:

    17z -> 0 results        (viewport ~0.2 mi: too tight)
    15z -> 6 results        (under-fills the Top-10)
    14z -> 10 results       (full depth; viewport ~1-2 mi ~ grid spacing)
    12z -> 10 results       (viewport ~5-8 mi: wider than the whole grid)

A center-vs-5mi-north comparison at 14z returned substantially DIFFERENT local
businesses (only national chains recurred; the 5-mi point surfaced "Battle Ground
Lock and Key"), confirming 14z preserves per-coordinate proximity signal — which
the Maps/Organic PRD's proximity / ranking-radius science requires.

This amendment (owner-approved) LOCKS the Maps coordinate zoom to 14z. It does NOT
change the research universe (industries/markets/geometry/coordinates/treatments):
only the DataForSEO Maps provider profile is versioned. The original 17z profile
(DFS_MAPS_V1) is preserved as the historical record; a new profile DFS_MAPS_V2
(14z) is added and the Maps surface config is repointed to it. See docs/adr/0006.
"""
from __future__ import annotations
import hashlib, json, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "manifest" / "SED_Collection_Manifest_v1_0.json"
OUT = ROOT / "supabase" / "migrations" / "022_amend_maps_zoom_14z.sql"
METH_CODE = "MANIFEST_V1_0"


def main() -> None:
    m = json.loads(MANIFEST.read_text())
    maps_settings = dict(m["provider_settings"]["maps"])
    # the frozen setting was "{lat},{lon},17z"; lock it to 14z
    old = maps_settings.get("location_coordinate")
    assert old and old.endswith("17z"), f"unexpected maps location_coordinate: {old!r}"
    maps_settings["location_coordinate"] = old.replace("17z", "14z")
    settings_json = json.dumps(maps_settings, sort_keys=True, ensure_ascii=False)
    settings_sha = hashlib.sha256(settings_json.encode()).hexdigest()
    settings_sql = "'" + settings_json.replace("'", "''") + "'::jsonb"

    out = []
    A = out.append
    A("-- Migration 022_amend_maps_zoom_14z")
    A("-- SED Local Search Intelligence Platform -- Stage-1 pilot methodology amendment")
    A("--")
    A("-- GENERATED by scripts/gen_amendment_022.py. Owner-approved lock of the Maps")
    A("-- coordinate zoom 17z -> 14z (Manifest v1.0 tagged the provider settings")
    A("-- PENDING_EXACT_ENDPOINT_LOCK; the pilot locks them). See docs/adr/0006.")
    A("--")
    A("-- Evidence (MKT008 center, 'locksmith near me'): 17z->0, 15z->6, 14z->10, 12z->10;")
    A("-- center vs 5mi-north at 14z returned different local businesses (per-coordinate")
    A("-- proximity signal preserved). Universe (industries/markets/geometry/coordinates/")
    A("-- treatments) is UNCHANGED; only the Maps provider profile is versioned.")
    A("-- Idempotent.")
    A("")
    A("-- 1) New Maps provider profile DFS_MAPS_V2 (14z), copied from DFS_MAPS_V1 (17z, kept as history).")
    A("insert into manifest.provider_profile")
    A("  (methodology_version_id, surface_id, provider_id, profile_code, method, post_endpoint,")
    A("   get_endpoint, language_code, device, operating_system, location_mode, location_template,")
    A("   result_depth, priority, max_tasks_per_post, settings, settings_sha256)")
    A("select pp.methodology_version_id, pp.surface_id, pp.provider_id, 'DFS_MAPS_V2', pp.method,")
    A("       pp.post_endpoint, pp.get_endpoint, pp.language_code, pp.device, pp.operating_system,")
    A("       pp.location_mode, '{lat},{lon},14z', pp.result_depth, pp.priority, pp.max_tasks_per_post,")
    A(f"       {settings_sql}, '{settings_sha}'")
    A("from manifest.provider_profile pp")
    A("join manifest.methodology_version mv on mv.methodology_version_id = pp.methodology_version_id")
    A(f"  and mv.methodology_code = '{METH_CODE}'")
    A("where pp.profile_code = 'DFS_MAPS_V1'")
    A("on conflict (methodology_version_id, profile_code) do nothing;")
    A("")
    A("-- 2) Repoint the Maps surface config to DFS_MAPS_V2 (14z).")
    A("update manifest.surface_config sc")
    A("set provider_profile_id = pp2.provider_profile_id")
    A("from manifest.surface s, manifest.methodology_version mv, manifest.provider_profile pp2")
    A("where sc.surface_id = s.surface_id and s.surface_code = 'maps'")
    A(f"  and mv.methodology_code = '{METH_CODE}' and sc.methodology_version_id = mv.methodology_version_id")
    A("  and pp2.methodology_version_id = mv.methodology_version_id and pp2.profile_code = 'DFS_MAPS_V2';")
    A("")
    A("-- 3) Record the amendment on the methodology version notes (append-only manifest table; update allowed).")
    A("update manifest.methodology_version")
    A("set notes = coalesce(notes,'') || ' | AMENDMENT 2026-09-13 (ADR-0006): Maps coordinate zoom locked 17z->14z after Stage-1 pilot probe (owner-approved).'")
    A(f"where methodology_code = '{METH_CODE}'")
    A("  and notes not like '%ADR-0006%';")
    A("")
    OUT.write_text("\n".join(out) + "\n")
    print(f"wrote {OUT}")
    print(f"DFS_MAPS_V2 location_coordinate = {maps_settings['location_coordinate']}  sha256={settings_sha}")


if __name__ == "__main__":
    main()
