#!/usr/bin/env python3
"""Generate supabase/migrations/029_aio_query_v2.sql from the frozen V2 condition library.

Deterministic: reads manifest/aio_query_v2_conditions.json (produced by
gen_aio_query_v2_json.py) and emits an additive, idempotent migration that seeds the
``AIO_QUERY_V2`` treatment set (250 treatments) and links every one of them to the
``aio`` surface (250 surface_treatment rows). ``AIO_QUERY_V1`` is left untouched
(retained as history). Both inserts are ``ON CONFLICT DO NOTHING`` and reference only
``EXISTS``-safe objects, so the file re-runs cleanly on every Railway deploy (it matches
the ``02[0-9]_*`` re-apply glob).

Run: python scripts/gen_migration_029_aio_query_v2.py   (--check verifies in place)
No DB, no network, no paid call.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "manifest" / "aio_query_v2_conditions.json"
OUT = ROOT / "supabase" / "migrations" / "029_aio_query_v2.sql"

MV = "MANIFEST_V1_0"
SURFACE = "aio"
# V2 surface_treatment sequences start above V1's aio block (1..250) to satisfy the
# unique(methodology_version_id, surface_id, sequence) constraint; V1 rows are untouched.
ST_SEQ_BASE = 250


def q(s: str) -> str:
    """SQL single-quoted literal with embedded quotes doubled."""
    return "'" + s.replace("'", "''") + "'"


def build_sql() -> str:
    data = json.loads(SRC.read_text())
    inds = data["industries"]
    set_code = data["treatment_set_code"]
    kind = data["treatment_kind"]
    src_ver = data["source_methodology_version"]

    treat_rows: list[str] = []
    st_rows: list[str] = []
    st_seq = ST_SEQ_BASE
    for ind in inds:
        icode = ind["industry_code"]
        for c in ind["conditions"]:
            meta = {
                "condition_id": c["condition_id"],
                "condition_role": c["condition_role"],
                "derivation": c["derivation"],
                "source_id": f"{icode}_{c['condition_id']}",
                "source_methodology_version": src_ver,
            }
            meta_json = json.dumps(meta, ensure_ascii=False, sort_keys=True)
            treat_rows.append(
                f"  ({q(icode)}, {q(set_code)}, {q(c['condition_id'])}, {q(kind)}, "
                f"{q(c['family'])}, null, {q(c['exact_template'])}, {c['sequence']}, "
                f"{'true' if c['city_slot_required'] else 'false'}, "
                f"{q(c['approval_basis'])}, {q(meta_json)}::jsonb)"
            )
            st_seq += 1
            st_rows.append(
                f"  ({q(SURFACE)}, {q(icode)}, {q(set_code)}, {q(c['condition_id'])}, {st_seq})"
            )

    n = len(treat_rows)
    header = f"""-- Migration 029_aio_query_v2
-- SED Local Search Intelligence Platform -- Stage-2 (AIO) methodology amendment
--
-- ADR-0011: AIO_QUERY_V2 -- conversational AIO conditions. Replaces V1's short
-- keyword variants C05-C08 with owner-signed-off conversational intents (C05
-- problem-led, C06 duress/immediate-need, C07 price/value, C08 criteria/decision);
-- C01-C04, C09, C10 are kept VERBATIM from AIO_QUERY_V1. Same 25x50 universe, same
-- GEOGRID13E_V1 geometry, same DFS_AIO_V2 provider, same 10-condition count -- ONLY
-- the treatment wording changes, so this is a treatment-set version bump, not a
-- population/estimand/geometry change.
--
-- ADDITIVE + IDEMPOTENT: seeds {n} AIO_QUERY_V2 treatments + {n} aio surface_treatment
-- links (sequences {ST_SEQ_BASE + 1}..{ST_SEQ_BASE + n}, above V1's 1..250 block).
-- AIO_QUERY_V1 is left in place, retained as history (reproduces the AIO-20260918
-- wave). Both inserts are ON CONFLICT DO NOTHING, so this file re-runs cleanly on
-- every deploy (matches the 02[0-9]_* re-apply glob in scripts/railway_run.sh).
--
-- GENERATED by scripts/gen_migration_029_aio_query_v2.py from
-- manifest/aio_query_v2_conditions.json -- do not hand-edit; regenerate instead.

-- treatment (AIO_QUERY_V2, {n} rows) -------------------------------------------
insert into manifest.treatment (methodology_version_id, industry_id, treatment_set_code,
  treatment_code, treatment_kind, family, core_query_class, exact_template, sequence,
  city_slot_required, is_locked, approval_basis, metadata)
select mv.methodology_version_id, i.industry_id, v.set_code, v.code,
  v.kind::manifest.treatment_kind, v.family, v.core_query_class, v.template, v.seq,
  v.city_slot, true, v.approval, v.meta
from (values
"""
    treat_block = ",\n".join(treat_rows)
    treat_tail = f"""
) as v(industry_code, set_code, code, kind, family, core_query_class, template, seq,
       city_slot, approval, meta)
join manifest.industry i on i.industry_code = v.industry_code
join manifest.methodology_version mv on mv.methodology_code = '{MV}'
on conflict (methodology_version_id, industry_id, treatment_set_code, treatment_code) do nothing;

-- surface_treatment (aio -> AIO_QUERY_V2, {n} rows) ----------------------------
insert into manifest.surface_treatment (methodology_version_id, surface_id, treatment_id, sequence, active)
select mv.methodology_version_id, s.surface_id, t.treatment_id, v.seq, true
from (values
"""
    st_block = ",\n".join(st_rows)
    st_tail = f"""
) as v(surface_code, industry_code, set_code, code, seq)
join manifest.surface s on s.surface_code = v.surface_code
join manifest.industry i on i.industry_code = v.industry_code
join manifest.methodology_version mv on mv.methodology_code = '{MV}'
join manifest.treatment t
  on t.methodology_version_id = mv.methodology_version_id and t.industry_id = i.industry_id
 and t.treatment_set_code = v.set_code and t.treatment_code = v.code
on conflict (methodology_version_id, surface_id, treatment_id) do nothing;
"""
    return header + treat_block + treat_tail + st_block + st_tail


def main() -> int:
    sql = build_sql()
    if "--check" in sys.argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != sql:
            print("OUT OF DATE: supabase/migrations/029_aio_query_v2.sql differs from generator output")
            return 1
        print("OK: 029_aio_query_v2.sql matches generator")
        return 0
    OUT.write_text(sql)
    print(f"wrote {OUT.relative_to(ROOT)} ({sql.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
