-- Migration 022_amend_maps_zoom_14z
-- SED Local Search Intelligence Platform -- Stage-1 pilot methodology amendment
--
-- GENERATED by scripts/gen_amendment_022.py. Owner-approved lock of the Maps
-- coordinate zoom 17z -> 14z (Manifest v1.0 tagged the provider settings
-- PENDING_EXACT_ENDPOINT_LOCK; the pilot locks them). See docs/adr/0006.
--
-- Evidence (MKT008 center, 'locksmith near me'): 17z->0, 15z->6, 14z->10, 12z->10;
-- center vs 5mi-north at 14z returned different local businesses (per-coordinate
-- proximity signal preserved). Universe (industries/markets/geometry/coordinates/
-- treatments) is UNCHANGED; only the Maps provider profile is versioned.
-- Idempotent.

-- 1) New Maps provider profile DFS_MAPS_V2 (14z), copied from DFS_MAPS_V1 (17z, kept as history).
insert into manifest.provider_profile
  (methodology_version_id, surface_id, provider_id, profile_code, method, post_endpoint,
   get_endpoint, language_code, device, operating_system, location_mode, location_template,
   result_depth, priority, max_tasks_per_post, settings, settings_sha256)
select pp.methodology_version_id, pp.surface_id, pp.provider_id, 'DFS_MAPS_V2', pp.method,
       pp.post_endpoint, pp.get_endpoint, pp.language_code, pp.device, pp.operating_system,
       pp.location_mode, '{lat},{lon},14z', pp.result_depth, pp.priority, pp.max_tasks_per_post,
       '{"depth": 10, "device": "desktop", "get_endpoint": "/v3/serp/google/maps/task_get/advanced/{id}", "language_code": "en", "location_coordinate": "{lat},{lon},14z", "max_tasks_per_post": 100, "method": "standard_async", "os": "windows", "post_endpoint": "/v3/serp/google/maps/task_post", "priority": 1, "search_places": false, "search_this_area": true}'::jsonb, '682dc5cea1f9f9d705f2e9ce35c99546819764f074b54f6d0a538f148a03a17e'
from manifest.provider_profile pp
join manifest.methodology_version mv on mv.methodology_version_id = pp.methodology_version_id
  and mv.methodology_code = 'MANIFEST_V1_0'
where pp.profile_code = 'DFS_MAPS_V1'
on conflict (methodology_version_id, profile_code) do nothing;

-- 2) Repoint the Maps surface config to DFS_MAPS_V2 (14z).
update manifest.surface_config sc
set provider_profile_id = pp2.provider_profile_id
from manifest.surface s, manifest.methodology_version mv, manifest.provider_profile pp2
where sc.surface_id = s.surface_id and s.surface_code = 'maps'
  and mv.methodology_code = 'MANIFEST_V1_0' and sc.methodology_version_id = mv.methodology_version_id
  and pp2.methodology_version_id = mv.methodology_version_id and pp2.profile_code = 'DFS_MAPS_V2';

-- 3) Record the amendment on the methodology version notes (append-only manifest table; update allowed).
update manifest.methodology_version
set notes = coalesce(notes,'') || ' | AMENDMENT 2026-09-13 (ADR-0006): Maps coordinate zoom locked 17z->14z after Stage-1 pilot probe (owner-approved).'
where methodology_code = 'MANIFEST_V1_0'
  and notes not like '%ADR-0006%';

