-- Migration 026_geogrid13e_efficient_grid
-- SED Local Search Intelligence Platform -- ADR-0009 acceptance (efficient geo-grid)
--
-- GENERATED by scripts/gen_migration_026.py. Accepts GEOGRID13E_V1: the efficient
-- 13-point unified grid (center + N/E/S/W @ 3/5 mi + NE/SE/SW/NW @ 4 mi), shared by
-- Maps/Organic AND AIO. It DROPS the low-yield 1-mile cardinal ring (kept in
-- MAPORG13_V1 history) and adds a 4-mile diagonal ring, on measured Full-Panel
-- saturation (docs/design/unified-geo-grid-v0_1.md). The 4-mile diagonals were
-- classified by the authoritative SED_GEO_ELIGIBILITY_CENSUS_2025_V1 gate (TIGER
-- 2025 AREAWATER water gate + US-state country gate; see
-- docs/design/data/geogrid13e_diagonal_water_classification.csv):
--   diagonals: 185 eligible / 14 water / 1 outside-country.
-- Combined with the copied C+3/5 cardinal skeleton (410 eligible of 450),
-- GEOGRID13E_V1 = 650 coordinates / 595 eligible.
--
-- Universe otherwise UNCHANGED (industries/markets/queries/treatments/cadence).
-- MAPORG13_V1 and AIO9_V1 are RETAINED as history; only the surface_config
-- geometry binding is repointed. Idempotent; mirrors 019 seeding + 022/025 repoint.
-- NOTE: diagonal water rows carry MTFCC + source + version; feature name/id are not
-- reconstructed (the national AREAWATER gpkg returns them but they are not needed
-- for the exclusion decision).

-- ============================================================================
-- 1) geometry_version GEOGRID13E_V1 (frozen amendment under MANIFEST_V1_0)
-- ============================================================================
insert into manifest.geometry_version (methodology_version_id, geometry_code, geometry_name,
  surface_group, generation_method, water_mask_version, status)
select mv.methodology_version_id, 'GEOGRID13E_V1',
  'Efficient 13-point unified grid (center + N/E/S/W @3/5 mi + NE/SE/SW/NW @4 mi)',
  'maps_organic_aio', 'WGS84_GEODESIC_DIRECT', 'SED_GEO_ELIGIBILITY_CENSUS_2025_V1', 'frozen'
from manifest.methodology_version mv
where mv.methodology_code = 'MANIFEST_V1_0'
on conflict (methodology_version_id, geometry_code) do nothing;

-- ============================================================================
-- 2) geometry_point (13 rows)
-- ============================================================================
insert into manifest.geometry_point (geometry_version_id, point_code, point_label, bearing_deg,
  distance_miles, full_geometry_member, nested_candidate_member, incremental_member, ordinal)
select gv.geometry_version_id, v.point_code, v.point_label, v.bearing_deg, v.distance_miles,
  v.full_geometry_member, v.nested_candidate_member, v.incremental_member, v.ordinal
from (values
  ('GEOGRID13E_V1', 'C', 'center', null, 0, true, false, false, 1),
  ('GEOGRID13E_V1', 'N3', 'N 3 mi', 0, 3, true, false, false, 2),
  ('GEOGRID13E_V1', 'E3', 'E 3 mi', 90, 3, true, false, false, 3),
  ('GEOGRID13E_V1', 'S3', 'S 3 mi', 180, 3, true, false, false, 4),
  ('GEOGRID13E_V1', 'W3', 'W 3 mi', 270, 3, true, false, false, 5),
  ('GEOGRID13E_V1', 'NE4', 'NE 4 mi', 45, 4, true, false, false, 6),
  ('GEOGRID13E_V1', 'SE4', 'SE 4 mi', 135, 4, true, false, false, 7),
  ('GEOGRID13E_V1', 'SW4', 'SW 4 mi', 225, 4, true, false, false, 8),
  ('GEOGRID13E_V1', 'NW4', 'NW 4 mi', 315, 4, true, false, false, 9),
  ('GEOGRID13E_V1', 'N5', 'N 5 mi', 0, 5, true, false, false, 10),
  ('GEOGRID13E_V1', 'E5', 'E 5 mi', 90, 5, true, false, false, 11),
  ('GEOGRID13E_V1', 'S5', 'S 5 mi', 180, 5, true, false, false, 12),
  ('GEOGRID13E_V1', 'W5', 'W 5 mi', 270, 5, true, false, false, 13)
) as v(geometry_code, point_code, point_label, bearing_deg, distance_miles,
       full_geometry_member, nested_candidate_member, incremental_member, ordinal)
join manifest.geometry_version gv on gv.geometry_code = v.geometry_code
join manifest.methodology_version mv on gv.methodology_version_id = mv.methodology_version_id
  and mv.methodology_code = 'MANIFEST_V1_0'
on conflict (geometry_version_id, point_code) do nothing;

-- ============================================================================
-- 3a) market_coordinate: copy center + 3/5-mile cardinals from MAPORG13_V1
--     (keeps their frozen eligibility; 9 points x 50 markets = 450 rows)
-- ============================================================================
insert into manifest.market_coordinate (methodology_version_id, market_id, geometry_point_id,
  latitude, longitude, eligibility, structural_exclusion_reason, water_feature_name,
  water_feature_mtfcc, water_feature_id, water_mask_source, water_mask_version, eligibility_decided_at)
select src.methodology_version_id, src.market_id, dst_gp.geometry_point_id,
  src.latitude, src.longitude, src.eligibility, src.structural_exclusion_reason,
  src.water_feature_name, src.water_feature_mtfcc, src.water_feature_id,
  src.water_mask_source, src.water_mask_version, src.eligibility_decided_at
from manifest.market_coordinate src
join manifest.geometry_point src_gp on src_gp.geometry_point_id = src.geometry_point_id
join manifest.geometry_version src_gv on src_gv.geometry_version_id = src_gp.geometry_version_id
  and src_gv.geometry_code = 'MAPORG13_V1'
join manifest.geometry_version dst_gv on dst_gv.methodology_version_id = src_gv.methodology_version_id
  and dst_gv.geometry_code = 'GEOGRID13E_V1'
join manifest.geometry_point dst_gp on dst_gp.geometry_version_id = dst_gv.geometry_version_id
  and dst_gp.point_code = src_gp.point_code
where src_gp.point_code in ('C','N3','E3','S3','W3','N5','E5','S5','W5')
on conflict (methodology_version_id, market_id, geometry_point_id) do nothing;

-- ============================================================================
-- 3b) market_coordinate: the 200 gated 4-mile diagonals (authoritative gate)
-- ============================================================================
insert into manifest.market_coordinate (methodology_version_id, market_id, geometry_point_id,
  latitude, longitude, eligibility, structural_exclusion_reason, water_feature_name,
  water_feature_mtfcc, water_feature_id, water_mask_source, water_mask_version, eligibility_decided_at)
select mv.methodology_version_id, mk.market_id, gp.geometry_point_id, v.latitude, v.longitude,
  v.eligibility::manifest.coordinate_eligibility, v.reason, v.wname, v.wmtfcc, v.whydro,
  v.wsrc, v.wmask, '2026-09-16T00:00:00Z'
from (values
  ('MKT001', 'GEOGRID13E_V1', 'NE4', 34.0948065, -118.1935739, 'eligible_land', null, null, null, null, null, null),
  ('MKT001', 'GEOGRID13E_V1', 'SE4', 34.0127334, -118.1936214, 'eligible_land', null, null, null, null, null, null),
  ('MKT001', 'GEOGRID13E_V1', 'SW4', 34.0127334, -118.2921786, 'eligible_land', null, null, null, null, null, null),
  ('MKT001', 'GEOGRID13E_V1', 'NW4', 34.0948065, -118.2922261, 'eligible_land', null, null, null, null, null, null),
  ('MKT002', 'GEOGRID13E_V1', 'NE4', 32.7580159, -117.1142342, 'eligible_land', null, null, null, null, null, null),
  ('MKT002', 'GEOGRID13E_V1', 'SE4', 32.6759251, -117.1142787, 'eligible_land', null, null, null, null, null, null),
  ('MKT002', 'GEOGRID13E_V1', 'SW4', 32.6759251, -117.2113413, 'structural_water_exclusion', 'Structural water exclusion (Census 2025 AREAWATER MTFCC H2053).', null, 'H2053', null, 'US Census Bureau 2025 TIGER/Line AREAWATER', 'SED_GEO_ELIGIBILITY_CENSUS_2025_V1'),
  ('MKT002', 'GEOGRID13E_V1', 'NW4', 32.7580159, -117.2113858, 'eligible_land', null, null, null, null, null, null),
  ('MKT003', 'GEOGRID13E_V1', 'NE4', 37.8202546, -122.367483, 'eligible_land', null, null, null, null, null, null),
  ('MKT003', 'GEOGRID13E_V1', 'SE4', 37.7382325, -122.3675401, 'eligible_land', null, null, null, null, null, null),
  ('MKT003', 'GEOGRID13E_V1', 'SW4', 37.7382325, -122.4708239, 'eligible_land', null, null, null, null, null, null),
  ('MKT003', 'GEOGRID13E_V1', 'NW4', 37.8202546, -122.470881, 'structural_water_exclusion', 'Structural water exclusion (Census 2025 AREAWATER MTFCC H2051).', null, 'H2051', null, 'US Census Bureau 2025 TIGER/Line AREAWATER', 'SED_GEO_ELIGIBILITY_CENSUS_2025_V1'),
  ('MKT004', 'GEOGRID13E_V1', 'NE4', 38.6230776, -121.4411687, 'eligible_land', null, null, null, null, null, null),
  ('MKT004', 'GEOGRID13E_V1', 'SE4', 38.5410668, -121.4412281, 'eligible_land', null, null, null, null, null, null),
  ('MKT004', 'GEOGRID13E_V1', 'SW4', 38.5410668, -121.5456499, 'eligible_land', null, null, null, null, null, null),
  ('MKT004', 'GEOGRID13E_V1', 'NW4', 38.6230776, -121.5457093, 'eligible_land', null, null, null, null, null, null),
  ('MKT005', 'GEOGRID13E_V1', 'NE4', 36.7806972, -119.7335177, 'eligible_land', null, null, null, null, null, null),
  ('MKT005', 'GEOGRID13E_V1', 'SE4', 36.6986607, -119.7335719, 'eligible_land', null, null, null, null, null, null),
  ('MKT005', 'GEOGRID13E_V1', 'SW4', 36.6986607, -119.8354481, 'eligible_land', null, null, null, null, null, null),
  ('MKT005', 'GEOGRID13E_V1', 'NW4', 36.7806972, -119.8355023, 'eligible_land', null, null, null, null, null, null),
  ('MKT006', 'GEOGRID13E_V1', 'NE4', 35.4137971, -118.9693233, 'eligible_land', null, null, null, null, null, null),
  ('MKT006', 'GEOGRID13E_V1', 'SE4', 35.3317418, -118.969374, 'eligible_land', null, null, null, null, null, null),
  ('MKT006', 'GEOGRID13E_V1', 'SW4', 35.3317418, -119.069506, 'eligible_land', null, null, null, null, null, null),
  ('MKT006', 'GEOGRID13E_V1', 'NW4', 35.4137971, -119.0695567, 'eligible_land', null, null, null, null, null, null),
  ('MKT007', 'GEOGRID13E_V1', 'NE4', 45.5559549, -122.6208124, 'eligible_land', null, null, null, null, null, null),
  ('MKT007', 'GEOGRID13E_V1', 'SE4', 45.4740431, -122.6208969, 'eligible_land', null, null, null, null, null, null),
  ('MKT007', 'GEOGRID13E_V1', 'SW4', 45.4740431, -122.7373231, 'eligible_land', null, null, null, null, null, null),
  ('MKT007', 'GEOGRID13E_V1', 'NW4', 45.5559549, -122.7374076, 'eligible_land', null, null, null, null, null, null),
  ('MKT008', 'GEOGRID13E_V1', 'NE4', 45.666595, -122.6170875, 'eligible_land', null, null, null, null, null, null),
  ('MKT008', 'GEOGRID13E_V1', 'SE4', 45.5846849, -122.6171725, 'eligible_land', null, null, null, null, null, null),
  ('MKT008', 'GEOGRID13E_V1', 'SW4', 45.5846849, -122.7338271, 'eligible_land', null, null, null, null, null, null),
  ('MKT008', 'GEOGRID13E_V1', 'NW4', 45.666595, -122.7339121, 'eligible_land', null, null, null, null, null, null),
  ('MKT009', 'GEOGRID13E_V1', 'NE4', 47.6448027, -122.2694188, 'structural_water_exclusion', 'Structural water exclusion (Census 2025 AREAWATER MTFCC H2030).', null, 'H2030', null, 'US Census Bureau 2025 TIGER/Line AREAWATER', 'SED_GEO_ELIGIBILITY_CENSUS_2025_V1'),
  ('MKT009', 'GEOGRID13E_V1', 'SE4', 47.562921, -122.2695133, 'eligible_land', null, null, null, null, null, null),
  ('MKT009', 'GEOGRID13E_V1', 'SW4', 47.562921, -122.3904887, 'eligible_land', null, null, null, null, null, null),
  ('MKT009', 'GEOGRID13E_V1', 'NW4', 47.6448027, -122.3905832, 'eligible_land', null, null, null, null, null, null),
  ('MKT010', 'GEOGRID13E_V1', 'NE4', 47.7007343, -117.3618831, 'eligible_land', null, null, null, null, null, null),
  ('MKT010', 'GEOGRID13E_V1', 'SE4', 47.6188534, -117.3619778, 'eligible_land', null, null, null, null, null, null),
  ('MKT010', 'GEOGRID13E_V1', 'SW4', 47.6188534, -117.4830822, 'eligible_land', null, null, null, null, null, null),
  ('MKT010', 'GEOGRID13E_V1', 'NW4', 47.7007343, -117.4831769, 'eligible_land', null, null, null, null, null, null),
  ('MKT011', 'GEOGRID13E_V1', 'NE4', 33.4898208, -112.0281196, 'eligible_land', null, null, null, null, null, null),
  ('MKT011', 'GEOGRID13E_V1', 'SE4', 33.4077396, -112.0281658, 'eligible_land', null, null, null, null, null, null),
  ('MKT011', 'GEOGRID13E_V1', 'SW4', 33.4077396, -112.1260342, 'eligible_land', null, null, null, null, null, null),
  ('MKT011', 'GEOGRID13E_V1', 'NW4', 33.4898208, -112.1260804, 'eligible_land', null, null, null, null, null, null),
  ('MKT012', 'GEOGRID13E_V1', 'NE4', 32.2636093, -110.9264494, 'eligible_land', null, null, null, null, null, null),
  ('MKT012', 'GEOGRID13E_V1', 'SE4', 32.181512, -110.9264928, 'eligible_land', null, null, null, null, null, null),
  ('MKT012', 'GEOGRID13E_V1', 'SW4', 32.181512, -111.0230272, 'eligible_land', null, null, null, null, null, null),
  ('MKT012', 'GEOGRID13E_V1', 'NW4', 32.2636093, -111.0230706, 'eligible_land', null, null, null, null, null, null),
  ('MKT013', 'GEOGRID13E_V1', 'NE4', 36.2084014, -115.0978815, 'eligible_land', null, null, null, null, null, null),
  ('MKT013', 'GEOGRID13E_V1', 'SE4', 36.126357, -115.0979342, 'eligible_land', null, null, null, null, null, null),
  ('MKT013', 'GEOGRID13E_V1', 'SW4', 36.126357, -115.1990658, 'eligible_land', null, null, null, null, null, null),
  ('MKT013', 'GEOGRID13E_V1', 'NW4', 36.2084014, -115.1991185, 'eligible_land', null, null, null, null, null, null),
  ('MKT014', 'GEOGRID13E_V1', 'NE4', 39.5671466, -119.759678, 'eligible_land', null, null, null, null, null, null),
  ('MKT014', 'GEOGRID13E_V1', 'SE4', 39.485149, -119.7597403, 'eligible_land', null, null, null, null, null, null),
  ('MKT014', 'GEOGRID13E_V1', 'SW4', 39.485149, -119.8655597, 'eligible_land', null, null, null, null, null, null),
  ('MKT014', 'GEOGRID13E_V1', 'NW4', 39.5671466, -119.865622, 'eligible_land', null, null, null, null, null, null),
  ('MKT015', 'GEOGRID13E_V1', 'NE4', 40.8005603, -111.8328659, 'eligible_land', null, null, null, null, null, null),
  ('MKT015', 'GEOGRID13E_V1', 'SE4', 40.7185802, -111.8329321, 'eligible_land', null, null, null, null, null, null),
  ('MKT015', 'GEOGRID13E_V1', 'SW4', 40.7185802, -111.9406799, 'eligible_land', null, null, null, null, null, null),
  ('MKT015', 'GEOGRID13E_V1', 'NW4', 40.8005603, -111.9407461, 'eligible_land', null, null, null, null, null, null),
  ('MKT016', 'GEOGRID13E_V1', 'NE4', 39.780425, -104.9357549, 'eligible_land', null, null, null, null, null, null),
  ('MKT016', 'GEOGRID13E_V1', 'SE4', 39.6984304, -104.9358178, 'eligible_land', null, null, null, null, null, null),
  ('MKT016', 'GEOGRID13E_V1', 'SW4', 39.6984304, -105.0419622, 'eligible_land', null, null, null, null, null, null),
  ('MKT016', 'GEOGRID13E_V1', 'NW4', 39.780425, -105.0420251, 'eligible_land', null, null, null, null, null, null),
  ('MKT017', 'GEOGRID13E_V1', 'NE4', 38.8766, -104.7685417, 'eligible_land', null, null, null, null, null, null),
  ('MKT017', 'GEOGRID13E_V1', 'SE4', 38.7945927, -104.7686019, 'eligible_land', null, null, null, null, null, null),
  ('MKT017', 'GEOGRID13E_V1', 'SW4', 38.7945927, -104.8733925, 'eligible_land', null, null, null, null, null, null),
  ('MKT017', 'GEOGRID13E_V1', 'NW4', 38.8766, -104.8734527, 'eligible_land', null, null, null, null, null, null),
  ('MKT018', 'GEOGRID13E_V1', 'NE4', 43.6560755, -116.1449523, 'eligible_land', null, null, null, null, null, null),
  ('MKT018', 'GEOGRID13E_V1', 'SE4', 43.5741364, -116.1450289, 'eligible_land', null, null, null, null, null, null),
  ('MKT018', 'GEOGRID13E_V1', 'SW4', 43.5741364, -116.2577311, 'eligible_land', null, null, null, null, null, null),
  ('MKT018', 'GEOGRID13E_V1', 'NW4', 43.6560755, -116.2578077, 'eligible_land', null, null, null, null, null, null),
  ('MKT019', 'GEOGRID13E_V1', 'NE4', 35.1286992, -106.6017286, 'eligible_land', null, null, null, null, null, null),
  ('MKT019', 'GEOGRID13E_V1', 'SE4', 35.04664, -106.6017786, 'eligible_land', null, null, null, null, null, null),
  ('MKT019', 'GEOGRID13E_V1', 'SW4', 35.04664, -106.7015614, 'eligible_land', null, null, null, null, null, null),
  ('MKT019', 'GEOGRID13E_V1', 'NW4', 35.1286992, -106.7016114, 'eligible_land', null, null, null, null, null, null),
  ('MKT020', 'GEOGRID13E_V1', 'NE4', 40.6308286, -105.0281067, 'eligible_land', null, null, null, null, null, null),
  ('MKT020', 'GEOGRID13E_V1', 'SE4', 40.5488461, -105.0281724, 'eligible_land', null, null, null, null, null, null),
  ('MKT020', 'GEOGRID13E_V1', 'SW4', 40.5488461, -105.1356476, 'eligible_land', null, null, null, null, null, null),
  ('MKT020', 'GEOGRID13E_V1', 'NW4', 40.6308286, -105.1357133, 'eligible_land', null, null, null, null, null, null),
  ('MKT021', 'GEOGRID13E_V1', 'NE4', 41.9248187, -87.5770734, 'structural_water_exclusion', 'Structural water exclusion (Census 2025 AREAWATER MTFCC H2030).', null, 'H2030', null, 'US Census Bureau 2025 TIGER/Line AREAWATER', 'SED_GEO_ELIGIBILITY_CENSUS_2025_V1'),
  ('MKT021', 'GEOGRID13E_V1', 'SE4', 41.8428548, -87.5771435, 'structural_water_exclusion', 'Structural water exclusion (Census 2025 AREAWATER MTFCC H2030).', null, 'H2030', null, 'US Census Bureau 2025 TIGER/Line AREAWATER', 'SED_GEO_ELIGIBILITY_CENSUS_2025_V1'),
  ('MKT021', 'GEOGRID13E_V1', 'SW4', 41.8428548, -87.6867565, 'eligible_land', null, null, null, null, null, null),
  ('MKT021', 'GEOGRID13E_V1', 'NW4', 41.9248187, -87.6868266, 'eligible_land', null, null, null, null, null, null),
  ('MKT022', 'GEOGRID13E_V1', 'NE4', 45.018245, -93.2076506, 'eligible_land', null, null, null, null, null, null),
  ('MKT022', 'GEOGRID13E_V1', 'SE4', 44.9363255, -93.2077328, 'eligible_land', null, null, null, null, null, null),
  ('MKT022', 'GEOGRID13E_V1', 'SW4', 44.9363255, -93.3230672, 'eligible_land', null, null, null, null, null, null),
  ('MKT022', 'GEOGRID13E_V1', 'NW4', 45.018245, -93.3231494, 'eligible_land', null, null, null, null, null, null),
  ('MKT023', 'GEOGRID13E_V1', 'NE4', 43.0826699, -87.8538914, 'structural_water_exclusion', 'Structural water exclusion (Census 2025 AREAWATER MTFCC H2030).', null, 'H2030', null, 'US Census Bureau 2025 TIGER/Line AREAWATER', 'SED_GEO_ELIGIBILITY_CENSUS_2025_V1'),
  ('MKT023', 'GEOGRID13E_V1', 'SE4', 43.0007225, -87.8539657, 'structural_water_exclusion', 'Structural water exclusion (Census 2025 AREAWATER MTFCC H2030).', null, 'H2030', null, 'US Census Bureau 2025 TIGER/Line AREAWATER', 'SED_GEO_ELIGIBILITY_CENSUS_2025_V1'),
  ('MKT023', 'GEOGRID13E_V1', 'SW4', 43.0007225, -87.9656143, 'eligible_land', null, null, null, null, null, null),
  ('MKT023', 'GEOGRID13E_V1', 'NW4', 43.0826699, -87.9656886, 'eligible_land', null, null, null, null, null, null),
  ('MKT024', 'GEOGRID13E_V1', 'NE4', 42.3704653, -82.9889972, 'eligible_land', null, null, null, null, null, null),
  ('MKT024', 'GEOGRID13E_V1', 'SE4', 42.2885078, -82.9890689, 'outside_country_exclusion', 'Non-center treatment point outside US international boundary (relocation prohibited).', null, null, null, 'US Census Bureau 2025 TIGER/Line International Boundary', 'SED_GEO_ELIGIBILITY_CENSUS_2025_V1'),
  ('MKT024', 'GEOGRID13E_V1', 'SW4', 42.2885078, -83.0994511, 'structural_water_exclusion', 'Structural water exclusion (Census 2025 AREAWATER MTFCC H3010).', null, 'H3010', null, 'US Census Bureau 2025 TIGER/Line AREAWATER', 'SED_GEO_ELIGIBILITY_CENSUS_2025_V1'),
  ('MKT024', 'GEOGRID13E_V1', 'NW4', 42.3704653, -83.0995228, 'eligible_land', null, null, null, null, null, null),
  ('MKT025', 'GEOGRID13E_V1', 'NE4', 40.0036333, -82.9500623, 'eligible_land', null, null, null, null, null, null),
  ('MKT025', 'GEOGRID13E_V1', 'SE4', 39.9216419, -82.9501259, 'eligible_land', null, null, null, null, null, null),
  ('MKT025', 'GEOGRID13E_V1', 'SW4', 39.9216419, -83.0566141, 'eligible_land', null, null, null, null, null, null),
  ('MKT025', 'GEOGRID13E_V1', 'NW4', 40.0036333, -83.0566777, 'eligible_land', null, null, null, null, null, null),
  ('MKT026', 'GEOGRID13E_V1', 'NE4', 39.1452197, -84.4667357, 'eligible_land', null, null, null, null, null, null),
  ('MKT026', 'GEOGRID13E_V1', 'SE4', 39.0632162, -84.4667967, 'eligible_land', null, null, null, null, null, null),
  ('MKT026', 'GEOGRID13E_V1', 'SW4', 39.0632162, -84.5719833, 'structural_water_exclusion', 'Structural water exclusion (Census 2025 AREAWATER MTFCC H2030).', null, 'H2030', null, 'US Census Bureau 2025 TIGER/Line AREAWATER', 'SED_GEO_ELIGIBILITY_CENSUS_2025_V1'),
  ('MKT026', 'GEOGRID13E_V1', 'NW4', 39.1452197, -84.5720443, 'eligible_land', null, null, null, null, null, null),
  ('MKT027', 'GEOGRID13E_V1', 'NE4', 39.8089548, -86.1003829, 'eligible_land', null, null, null, null, null, null),
  ('MKT027', 'GEOGRID13E_V1', 'SE4', 39.7269606, -86.100446, 'eligible_land', null, null, null, null, null, null),
  ('MKT027', 'GEOGRID13E_V1', 'SW4', 39.7269606, -86.206634, 'eligible_land', null, null, null, null, null, null),
  ('MKT027', 'GEOGRID13E_V1', 'NW4', 39.8089548, -86.2066971, 'eligible_land', null, null, null, null, null, null),
  ('MKT028', 'GEOGRID13E_V1', 'NE4', 38.6678053, -90.1471032, 'eligible_land', null, null, null, null, null, null),
  ('MKT028', 'GEOGRID13E_V1', 'SE4', 38.5857951, -90.1471628, 'eligible_land', null, null, null, null, null, null),
  ('MKT028', 'GEOGRID13E_V1', 'SW4', 38.5857951, -90.2516492, 'eligible_land', null, null, null, null, null, null),
  ('MKT028', 'GEOGRID13E_V1', 'NW4', 38.6678053, -90.2517088, 'eligible_land', null, null, null, null, null, null),
  ('MKT029', 'GEOGRID13E_V1', 'NE4', 39.1416098, -94.5252684, 'eligible_land', null, null, null, null, null, null),
  ('MKT029', 'GEOGRID13E_V1', 'SE4', 39.0596062, -94.5253294, 'eligible_land', null, null, null, null, null, null),
  ('MKT029', 'GEOGRID13E_V1', 'SW4', 39.0596062, -94.6305106, 'eligible_land', null, null, null, null, null, null),
  ('MKT029', 'GEOGRID13E_V1', 'NW4', 39.1416098, -94.6305716, 'eligible_land', null, null, null, null, null, null),
  ('MKT030', 'GEOGRID13E_V1', 'NE4', 43.0102304, -85.6156771, 'eligible_land', null, null, null, null, null, null),
  ('MKT030', 'GEOGRID13E_V1', 'SE4', 42.9282821, -85.6157512, 'eligible_land', null, null, null, null, null, null),
  ('MKT030', 'GEOGRID13E_V1', 'SW4', 42.9282821, -85.7272688, 'eligible_land', null, null, null, null, null, null),
  ('MKT030', 'GEOGRID13E_V1', 'NW4', 43.0102304, -85.7273429, 'eligible_land', null, null, null, null, null, null),
  ('MKT031', 'GEOGRID13E_V1', 'NE4', 32.8173055, -96.748332, 'eligible_land', null, null, null, null, null, null),
  ('MKT031', 'GEOGRID13E_V1', 'SE4', 32.7352154, -96.7483766, 'eligible_land', null, null, null, null, null, null),
  ('MKT031', 'GEOGRID13E_V1', 'SW4', 32.7352154, -96.8455034, 'eligible_land', null, null, null, null, null, null),
  ('MKT031', 'GEOGRID13E_V1', 'NW4', 32.8173055, -96.845548, 'eligible_land', null, null, null, null, null, null),
  ('MKT032', 'GEOGRID13E_V1', 'NE4', 29.8012358, -95.3222868, 'eligible_land', null, null, null, null, null, null),
  ('MKT032', 'GEOGRID13E_V1', 'SE4', 29.7191072, -95.3223251, 'eligible_land', null, null, null, null, null, null),
  ('MKT032', 'GEOGRID13E_V1', 'SW4', 29.7191072, -95.4164149, 'eligible_land', null, null, null, null, null, null),
  ('MKT032', 'GEOGRID13E_V1', 'NW4', 29.8012358, -95.4164532, 'eligible_land', null, null, null, null, null, null),
  ('MKT033', 'GEOGRID13E_V1', 'NE4', 30.3058425, -97.6998774, 'eligible_land', null, null, null, null, null, null),
  ('MKT033', 'GEOGRID13E_V1', 'SE4', 30.2237202, -97.6999168, 'eligible_land', null, null, null, null, null, null),
  ('MKT033', 'GEOGRID13E_V1', 'SW4', 30.2237202, -97.7944832, 'eligible_land', null, null, null, null, null, null),
  ('MKT033', 'GEOGRID13E_V1', 'NW4', 30.3058425, -97.7945226, 'eligible_land', null, null, null, null, null, null),
  ('MKT034', 'GEOGRID13E_V1', 'NE4', 29.4656448, -98.4482172, 'eligible_land', null, null, null, null, null, null),
  ('MKT034', 'GEOGRID13E_V1', 'SE4', 29.383512, -98.4482549, 'eligible_land', null, null, null, null, null, null),
  ('MKT034', 'GEOGRID13E_V1', 'SW4', 29.383512, -98.5420343, 'eligible_land', null, null, null, null, null, null),
  ('MKT034', 'GEOGRID13E_V1', 'NW4', 29.4656448, -98.542072, 'eligible_land', null, null, null, null, null, null),
  ('MKT035', 'GEOGRID13E_V1', 'NE4', 36.2082314, -86.7279916, 'eligible_land', null, null, null, null, null, null),
  ('MKT035', 'GEOGRID13E_V1', 'SE4', 36.126187, -86.7280443, 'eligible_land', null, null, null, null, null, null),
  ('MKT035', 'GEOGRID13E_V1', 'SW4', 36.126187, -86.8291757, 'eligible_land', null, null, null, null, null, null),
  ('MKT035', 'GEOGRID13E_V1', 'NW4', 36.2082314, -86.8292284, 'eligible_land', null, null, null, null, null, null),
  ('MKT036', 'GEOGRID13E_V1', 'NE4', 35.1894387, -90.0009414, 'eligible_land', null, null, null, null, null, null),
  ('MKT036', 'GEOGRID13E_V1', 'SE4', 35.1073804, -90.0009916, 'eligible_land', null, null, null, null, null, null),
  ('MKT036', 'GEOGRID13E_V1', 'SW4', 35.1073804, -90.1008484, 'eligible_land', null, null, null, null, null, null),
  ('MKT036', 'GEOGRID13E_V1', 'NW4', 35.1894387, -90.1008986, 'structural_water_exclusion', 'Structural water exclusion (Census 2025 AREAWATER MTFCC H3010).', null, 'H3010', null, 'US Census Bureau 2025 TIGER/Line AREAWATER', 'SED_GEO_ELIGIBILITY_CENSUS_2025_V1'),
  ('MKT037', 'GEOGRID13E_V1', 'NE4', 33.7896487, -84.3414396, 'eligible_land', null, null, null, null, null, null),
  ('MKT037', 'GEOGRID13E_V1', 'SE4', 33.7075715, -84.3414864, 'eligible_land', null, null, null, null, null, null),
  ('MKT037', 'GEOGRID13E_V1', 'SW4', 33.7075715, -84.4396936, 'eligible_land', null, null, null, null, null, null),
  ('MKT037', 'GEOGRID13E_V1', 'NW4', 33.7896487, -84.4397404, 'eligible_land', null, null, null, null, null, null),
  ('MKT038', 'GEOGRID13E_V1', 'NE4', 35.2625708, -80.7892847, 'eligible_land', null, null, null, null, null, null),
  ('MKT038', 'GEOGRID13E_V1', 'SE4', 35.1805135, -80.789335, 'eligible_land', null, null, null, null, null, null),
  ('MKT038', 'GEOGRID13E_V1', 'SW4', 35.1805135, -80.8892812, 'eligible_land', null, null, null, null, null, null),
  ('MKT038', 'GEOGRID13E_V1', 'NW4', 35.2625708, -80.8893315, 'eligible_land', null, null, null, null, null, null),
  ('MKT039', 'GEOGRID13E_V1', 'NE4', 35.8198132, -78.5925594, 'eligible_land', null, null, null, null, null, null),
  ('MKT039', 'GEOGRID13E_V1', 'SE4', 35.7377634, -78.5926111, 'eligible_land', null, null, null, null, null, null),
  ('MKT039', 'GEOGRID13E_V1', 'SW4', 35.7377634, -78.6932489, 'eligible_land', null, null, null, null, null, null),
  ('MKT039', 'GEOGRID13E_V1', 'NW4', 35.8198132, -78.6933006, 'eligible_land', null, null, null, null, null, null),
  ('MKT040', 'GEOGRID13E_V1', 'NE4', 33.5605803, -86.7617997, 'eligible_land', null, null, null, null, null, null),
  ('MKT040', 'GEOGRID13E_V1', 'SE4', 33.4785001, -86.761846, 'eligible_land', null, null, null, null, null, null),
  ('MKT040', 'GEOGRID13E_V1', 'SW4', 33.4785001, -86.859794, 'eligible_land', null, null, null, null, null, null),
  ('MKT040', 'GEOGRID13E_V1', 'NW4', 33.5605803, -86.8598403, 'eligible_land', null, null, null, null, null, null),
  ('MKT041', 'GEOGRID13E_V1', 'NE4', 25.7687656, -80.1883881, 'eligible_land', null, null, null, null, null, null),
  ('MKT041', 'GEOGRID13E_V1', 'SE4', 25.6865891, -80.1884192, 'structural_water_exclusion', 'Structural water exclusion (Census 2025 AREAWATER MTFCC H2051).', null, 'H2051', null, 'US Census Bureau 2025 TIGER/Line AREAWATER', 'SED_GEO_ELIGIBILITY_CENSUS_2025_V1'),
  ('MKT041', 'GEOGRID13E_V1', 'SW4', 25.6865891, -80.2791112, 'eligible_land', null, null, null, null, null, null),
  ('MKT041', 'GEOGRID13E_V1', 'NW4', 25.7687656, -80.2791423, 'eligible_land', null, null, null, null, null, null),
  ('MKT042', 'GEOGRID13E_V1', 'NE4', 27.9887274, -82.4109676, 'eligible_land', null, null, null, null, null, null),
  ('MKT042', 'GEOGRID13E_V1', 'SE4', 27.9065768, -82.4110026, 'eligible_land', null, null, null, null, null, null),
  ('MKT042', 'GEOGRID13E_V1', 'SW4', 27.9065768, -82.5034774, 'eligible_land', null, null, null, null, null, null),
  ('MKT042', 'GEOGRID13E_V1', 'NW4', 27.9887274, -82.5035124, 'eligible_land', null, null, null, null, null, null),
  ('MKT043', 'GEOGRID13E_V1', 'NE4', 28.5786851, -81.3331525, 'eligible_land', null, null, null, null, null, null),
  ('MKT043', 'GEOGRID13E_V1', 'SE4', 28.4965415, -81.3331885, 'eligible_land', null, null, null, null, null, null),
  ('MKT043', 'GEOGRID13E_V1', 'SW4', 28.4965415, -81.4261727, 'eligible_land', null, null, null, null, null, null),
  ('MKT043', 'GEOGRID13E_V1', 'NW4', 28.5786851, -81.4262087, 'eligible_land', null, null, null, null, null, null),
  ('MKT044', 'GEOGRID13E_V1', 'NE4', 30.37075, -81.6114672, 'eligible_land', null, null, null, null, null, null),
  ('MKT044', 'GEOGRID13E_V1', 'SE4', 30.2886286, -81.6115067, 'eligible_land', null, null, null, null, null, null),
  ('MKT044', 'GEOGRID13E_V1', 'SW4', 30.2886286, -81.7061353, 'eligible_land', null, null, null, null, null, null),
  ('MKT044', 'GEOGRID13E_V1', 'NW4', 30.37075, -81.7061748, 'eligible_land', null, null, null, null, null, null),
  ('MKT045', 'GEOGRID13E_V1', 'NE4', 37.5819913, -77.3814262, 'eligible_land', null, null, null, null, null, null),
  ('MKT045', 'GEOGRID13E_V1', 'SE4', 37.4999659, -77.3814826, 'eligible_land', null, null, null, null, null, null),
  ('MKT045', 'GEOGRID13E_V1', 'SW4', 37.4999659, -77.4844374, 'eligible_land', null, null, null, null, null, null),
  ('MKT045', 'GEOGRID13E_V1', 'NW4', 37.5819913, -77.4844938, 'eligible_land', null, null, null, null, null, null),
  ('MKT046', 'GEOGRID13E_V1', 'NE4', 38.9360013, -76.9788408, 'eligible_land', null, null, null, null, null, null),
  ('MKT046', 'GEOGRID13E_V1', 'SE4', 38.8539948, -76.9789011, 'eligible_land', null, null, null, null, null, null),
  ('MKT046', 'GEOGRID13E_V1', 'SW4', 38.8539948, -77.0837789, 'eligible_land', null, null, null, null, null, null),
  ('MKT046', 'GEOGRID13E_V1', 'NW4', 38.9360013, -77.0838392, 'eligible_land', null, null, null, null, null, null),
  ('MKT047', 'GEOGRID13E_V1', 'NE4', 39.3318683, -76.557896, 'eligible_land', null, null, null, null, null, null),
  ('MKT047', 'GEOGRID13E_V1', 'SE4', 39.2498675, -76.5579576, 'structural_water_exclusion', 'Structural water exclusion (Census 2025 AREAWATER MTFCC H3010).', null, 'H3010', null, 'US Census Bureau 2025 TIGER/Line AREAWATER', 'SED_GEO_ELIGIBILITY_CENSUS_2025_V1'),
  ('MKT047', 'GEOGRID13E_V1', 'SW4', 39.2498675, -76.6634224, 'eligible_land', null, null, null, null, null, null),
  ('MKT047', 'GEOGRID13E_V1', 'NW4', 39.3318683, -76.663484, 'eligible_land', null, null, null, null, null, null),
  ('MKT048', 'GEOGRID13E_V1', 'NE4', 39.9933134, -75.1102103, 'eligible_land', null, null, null, null, null, null),
  ('MKT048', 'GEOGRID13E_V1', 'SE4', 39.9113219, -75.1102739, 'eligible_land', null, null, null, null, null, null),
  ('MKT048', 'GEOGRID13E_V1', 'SW4', 39.9113219, -75.2167461, 'eligible_land', null, null, null, null, null, null),
  ('MKT048', 'GEOGRID13E_V1', 'NW4', 39.9933134, -75.2168097, 'eligible_land', null, null, null, null, null, null),
  ('MKT049', 'GEOGRID13E_V1', 'NE4', 40.7537176, -73.9521078, 'eligible_land', null, null, null, null, null, null),
  ('MKT049', 'GEOGRID13E_V1', 'SE4', 40.6717369, -73.9521738, 'eligible_land', null, null, null, null, null, null),
  ('MKT049', 'GEOGRID13E_V1', 'SW4', 40.6717369, -74.0598462, 'structural_water_exclusion', 'Structural water exclusion (Census 2025 AREAWATER MTFCC H2051).', null, 'H2051', null, 'US Census Bureau 2025 TIGER/Line AREAWATER', 'SED_GEO_ELIGIBILITY_CENSUS_2025_V1'),
  ('MKT049', 'GEOGRID13E_V1', 'NW4', 40.7537176, -74.0599122, 'eligible_land', null, null, null, null, null, null),
  ('MKT050', 'GEOGRID13E_V1', 'NE4', 42.4013951, -71.0026701, 'eligible_land', null, null, null, null, null, null),
  ('MKT050', 'GEOGRID13E_V1', 'SE4', 42.319438, -71.0027419, 'structural_water_exclusion', 'Structural water exclusion (Census 2025 AREAWATER MTFCC H2051).', null, 'H2051', null, 'US Census Bureau 2025 TIGER/Line AREAWATER', 'SED_GEO_ELIGIBILITY_CENSUS_2025_V1'),
  ('MKT050', 'GEOGRID13E_V1', 'SW4', 42.319438, -71.1131781, 'eligible_land', null, null, null, null, null, null),
  ('MKT050', 'GEOGRID13E_V1', 'NW4', 42.4013951, -71.1132499, 'eligible_land', null, null, null, null, null, null)
) as v(market_code, geometry_code, point_code, latitude, longitude, eligibility, reason,
       wname, wmtfcc, whydro, wsrc, wmask)
join manifest.market mk on mk.market_code = v.market_code
join manifest.geometry_version gv on gv.geometry_code = v.geometry_code
join manifest.geometry_point gp on gp.geometry_version_id = gv.geometry_version_id and gp.point_code = v.point_code
join manifest.methodology_version mv on mv.methodology_version_id = gv.methodology_version_id
  and mv.methodology_code = 'MANIFEST_V1_0'
on conflict (methodology_version_id, market_id, geometry_point_id) do nothing;

-- ============================================================================
-- 4) Repoint maps / organic / aio surface_config to GEOGRID13E_V1
--    (MAPORG13_V1 + AIO9_V1 retained as history)
-- ============================================================================
update manifest.surface_config sc
set geometry_version_id = gnew.geometry_version_id
from manifest.surface s, manifest.methodology_version mv, manifest.geometry_version gnew
where sc.surface_id = s.surface_id and s.surface_code in ('maps','organic','aio')
  and mv.methodology_code = 'MANIFEST_V1_0' and sc.methodology_version_id = mv.methodology_version_id
  and gnew.methodology_version_id = mv.methodology_version_id and gnew.geometry_code = 'GEOGRID13E_V1';

-- ============================================================================
-- 5) Record the amendment (append-only manifest table; update allowed)
-- ============================================================================
update manifest.methodology_version
set notes = coalesce(notes,'') || ' | AMENDMENT 2026-09-16 (ADR-0009): accepted GEOGRID13E_V1 (efficient 13-point unified grid: center + N/E/S/W @3/5 mi + NE/SE/SW/NW @4 mi); dropped the 1-mile cardinal ring (MAPORG13_V1 retained as history); maps/organic/aio surface_config repointed to GEOGRID13E_V1; AIO9_V1 retained as history.'
where methodology_code = 'MANIFEST_V1_0'
  and notes not like '%ADR-0009%';
